POST http://localhost:8080/events HTTP/1.1
Content-Type: application/json

{
    "name": "Smile",
    "description": "User event test",
    "location": "cardiff",
    "dateTime": "2025-01-01T15:30:00.000Z"   
}